# Generated by Django 4.1.5 on 2023-02-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_influenceur_date_joined_influenceur_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
